//////////////////////////////////////////////////////////////////
// LED DRIVER - TLC5916
//
// LIBRARY FOR 8 CHANNEL CONSTANT CURRENT SINK TLC5916 FROM
// TEXAS INSTRUMENTS
//
// NOTE : DEPENDS ON GPIO LIBRARY. GPIO LIBRARY WOULD BE PLATFORM
//		  DEPENDENT (AVR/ARM/ESP)
//
// FEBRUARY 6, 2017
//
// ANKIT BHATNAGAR
// ANKIT.BHATNAGARINDIA@GMAIL.COM
//////////////////////////////////////////////////////////////////

#include "LED_DRIVER_TLC5916.h"

//INTERNAL FUNCTIONS/////////////////
static GPIO_HIGH(uint8_t gpio_num)
{
	//FUNCTION USED BY LIBRARY TO SET GPIO PIN HIGH
	//CUSTOMIZE AS PER THE MCU PLATFORM
	GPIO_OUTPUT_SET(gpio_num, 1);
}

static GPIO_LOW(uint8_t gpio_num)
{
	//FUNCTION USED BY LIBRARY TO SET GPIO PIN LOW
	//CUSTOMIZE AS PER THE MCU PLATFORM
	GPIO_OUTPUT_SET(gpio_num, 0);
}

static SYS_DELAY_MS(uint16_t delay_val)
{
	//FUNCTION USED BY LIBRARY TO GIVE DELAY
	//CUSTOMIZE AS PER THE MCU PLATFORM
	os_delay(delay_val);
}


void LED_DRIVER_TLC5916_Init(void)
{
	//INITIALIZE TLC5916 AND TURN OFF THE DISPLAY
	//PIN DIRECTIONS SETTING RESPONSIBILITY OF THE USER PROGRAM
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		GPIO_HIGH(LED_DRIVER_TLC5916_GPIO_OE);
	}
}
void LED_DRIVER_TLC5916_Turn_On(void)
{
	//TURN ON DISPLAY (OE) OF TLC5916
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		GPIO_LOW(LED_DRIVER_TLC5916_GPIO_OE);
	}
}

void LED_DRIVER_TLC5916_Turn_Off(void)
{
	//TURN OFF DISPLAY (OE) OF TLC5916
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		GPIO_HIGH(LED_DRIVER_TLC5916_GPIO_OE);
	}
}

void LED_DRIVER_TLC5916_Send_Value(uint8_t* val)
{
	//SEND 8 BIT VALUE TO TLC5916 AND LATCH IT
	//TO IT'S OUTPUT
	//ARGUMENT IS ARRAY BECAUSE MULTIPLE TLC5916
	//CAN BE DAISY CHAINED BASED ON THE USER DEFINE
	//'LED_DRIVER_TLC5916_NUM'
	
	uint8_t j = 0;
	uint8_t i = LED_DRIVER_TLC5916_NUM;
	
	while(i != 0)
	{
		GPIO_LOW(LED_DRIVER_TLC5916_GPIO_CLK);
		for(j = 0; j < 16; j++)
		{
			GPIO_HIGH(LED_DRIVER_TLC5916_GPIO_CLK);
			if(val[i - 1] & (1 << j))
			{
				GPIO_HIGH(LED_DRIVER_TLC5916_GPIO_SDI);
			}
			else
			{
				GPIO_LOW(LED_DRIVER_TLC5916_GPIO_SDI);
			}
			SYS_DELAY_MS(LED_DRIVER_TLC5916_CLK_DELAY_MS);
			GPIO_LOW(LED_DRIVER_TLC5916_GPIO_CLK);
			SYS_DELAY_MS(LED_DRIVER_TLC5916_CLK_DELAY_MS);
		}
		i--;
	}
	//LATCH THE NEW VALUES
	GPIO_HIGH(LED_DRIVER_TLC5916_GPIO_LE);
	SYS_DELAY_MS(LED_DRIVER_TLC5916_CLK_DELAY_MS);
	GPIO_LOW(LED_DRIVER_TLC5916_GPIO_LE);
}
