//////////////////////////////////////////////////////////////////
// LED DRIVER - TLC5916
//
// LIBRARY FOR 8 CHANNEL CONSTANT CURRENT SINK TLC5916 FROM
// TEXAS INSTRUMENTS
//
// NOTE : DEPENDS ON GPIO LIBRARY. GPIO LIBRARY WOULD BE PLATFORM
//		  DEPENDENT (AVR/ARM/ESP)
//
// FEBRUARY 6, 2017
//
// ANKIT BHATNAGAR
// ANKIT.BHATNAGARINDIA@GMAIL.COM
//////////////////////////////////////////////////////////////////

#include "LED_DRIVER_TLC5916.h"


void LED_DRIVER_TLC5916_Init(void)
{
	//INITIALIZE TLC5916 AND TURN OFF THE DISPLAY
	//PIN DIRECTIONS SETTING RESPONSIBILITY OF THE USER PROGRAM
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_OE, 1);
	}
}
void LED_DRIVER_TLC5916_Turn_On(void)
{
	//TURN ON DISPLAY (OE) OF TLC5916
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_OE, 0);
	}
}

void LED_DRIVER_TLC5916_Turn_Off(void)
{
	//TURN OFF DISPLAY (OE) OF TLC5916
	
	if(LED_DRIVER_TLC5916_HAS_OE_CONTROL)
	{
		//LIBRARY CONTROLS THE /OE LINE
		TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_OE, 1);
	}
}

void LED_DRIVER_TLC5916_Send_Value(uint8_t* val)
{
	//SEND 8 BIT VALUE TO TLC5916 AND LATCH IT
	//TO IT'S OUTPUT
	//ARGUMENT IS ARRAY BECAUSE MULTIPLE TLC5916
	//CAN BE DAISY CHAINED BASED ON THE USER DEFINE
	//'LED_DRIVER_TLC5916_NUM'
	
	uint8_t j = 0;
	uint8_t i = LED_DRIVER_TLC5916_NUM;
	
	while(i != 0)
	{
		TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_CLK, 0);
		for(j = 0; j < 16; j++)
		{
			TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_CLK, 1);
			if(val[i - 1] & (1 << j))
			{
				TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_SDI, 1);
			}
			else
			{
				TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_SDI, 0);
			}
			TLC5916_SYS_DELAY_US(LED_DRIVER_TLC5916_CLK_DELAY_MS * 1000);
			TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_CLK, 0);
			TLC5916_SYS_DELAY_US(LED_DRIVER_TLC5916_CLK_DELAY_MS * 1000);
		}
		i--;
	}
	//LATCH THE NEW VALUES
	TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_LE, 1);
	TLC5916_SYS_DELAY_US(LED_DRIVER_TLC5916_CLK_DELAY_MS * 1000);
	TLC5916_GPIO_SET(LED_DRIVER_TLC5916_GPIO_LE, 0);
}
